
services:
  devopsdb:
    image: shaikmustafa/flm-oct:db
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  application:
    image: shaikmustafa/flm-oct:javaapp
    ports:
      - "1114:8080"
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

