
services:
  devopsdb:
    image: starwhat/project:db
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  application:
    image: starwhat/project:javaapp
    ports:
      - "1114:8080"
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay

